import { PrismaClient, ActivityType, AgeGroup, SkillArea } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding Skillozen database...')

  await prisma.admin.upsert({
    where: { email: 'admin@skillozen.com' },
    update: {},
    create: { email: 'admin@skillozen.com', passwordHash: 'unused' },
  })

  const badges = [
    { id: 'first-step',    name: 'First Step',     emoji: '👶', description: 'Completed your first activity',    condition: 'Complete 1 activity' },
    { id: 'explorer',      name: 'Explorer',        emoji: '🧭', description: 'Completed 10 activities',          condition: 'Complete 10 activities' },
    { id: 'thinker',       name: 'Thinker',         emoji: '🧠', description: 'Mastered Critical Thinking',       condition: 'Score 70+ in Critical Thinking',  skill: SkillArea.CRITICAL_THINKING },
    { id: 'communicator',  name: 'Communicator',    emoji: '🗣️', description: 'Mastered Communication',          condition: 'Score 70+ in Communication',      skill: SkillArea.COMMUNICATION },
    { id: 'creator',       name: 'Creator',         emoji: '🎨', description: 'Mastered Creativity',             condition: 'Score 70+ in Creativity',         skill: SkillArea.CREATIVITY },
    { id: 'digital-native',name: 'Digital Native',  emoji: '💻', description: 'Mastered Digital Literacy',       condition: 'Score 70+ in Digital Literacy',   skill: SkillArea.DIGITAL_LITERACY },
    { id: 'empathy-star',  name: 'Empathy Star',    emoji: '💛', description: 'Mastered Social-Emotional',       condition: 'Score 70+ in SEL',               skill: SkillArea.SOCIAL_EMOTIONAL },
    { id: 'week-warrior',  name: 'Week Warrior',    emoji: '🔥', description: '7-day activity streak',           condition: 'Maintain a 7-day streak' },
    { id: 'xp-legend',     name: 'XP Legend',       emoji: '⚡', description: 'Earned 500 XP',                  condition: 'Earn 500 XP total' },
    { id: 'assessment-ace',name: 'Assessment Ace',  emoji: '🏆', description: 'Scored 80+ in assessment',       condition: 'Overall assessment score 80+' },
  ]

  for (const badge of badges) {
    await prisma.badge.upsert({
      where: { id: badge.id },
      update: {},
      create: badge,
    })
  }

  // Delete existing activity logs first then activities
  await prisma.activityLog.deleteMany({})
  await prisma.activity.deleteMany({})

  const activities = [
    // ─── AGES 4-7 (EARLY) ─────────────────────────────────────────────────────

    // CRITICAL THINKING - Early
    {
      id: 'act-001',
      title: 'The Magic Sorting Hat',
      description: 'Help the magic hat sort animals into the right homes! Practice logical thinking.',
      skill: SkillArea.CRITICAL_THINKING,
      ageGroup: [AgeGroup.EARLY],
      type: ActivityType.GAME,
      difficulty: 1,
      xpReward: 15,
      durationMin: 5,
      content: {
        story: 'The magic sorting hat needs your help! Each animal needs to go to the right home.',
        question: 'A fish, a bird, and a dog are looking for homes. Which animal lives in water?',
        options: ['The Bird', 'The Fish', 'The Dog', 'All of them'],
        correct: 1,
        funFact: 'Fish breathe through gills which only work underwater! That is why they need water to live.',
        encouragement: 'Amazing thinking! You are a sorting superstar!',
      },
      tags: ['logic', 'animals', 'fun'],
      isOffline: true,
    },
    {
      id: 'act-002',
      title: 'What Comes Next?',
      description: 'Look at the pattern and figure out what comes next! Train your brain.',
      skill: SkillArea.CRITICAL_THINKING,
      ageGroup: [AgeGroup.EARLY],
      type: ActivityType.GAME,
      difficulty: 1,
      xpReward: 15,
      durationMin: 5,
      content: {
        story: 'Detective Dot loves patterns! Can you help her figure out what comes next?',
        question: 'Sun, Moon, Sun, Moon, Sun, ___? What comes next in the pattern?',
        options: ['Sun', 'Moon', 'Star', 'Cloud'],
        correct: 1,
        funFact: 'Patterns are everywhere! In music, art, nature and even in numbers. Spotting patterns is a superpower!',
        encouragement: 'You are a pattern detective! Great job!',
      },
      tags: ['patterns', 'logic', 'fun'],
      isOffline: true,
    },
    {
      id: 'act-003',
      title: 'The Wobbly Bridge',
      description: 'Help the bunny cross the bridge safely by making smart choices!',
      skill: SkillArea.CRITICAL_THINKING,
      ageGroup: [AgeGroup.EARLY],
      type: ActivityType.GAME,
      difficulty: 2,
      xpReward: 20,
      durationMin: 7,
      content: {
        story: 'Benny the Bunny needs to cross a wobbly bridge. The bridge can only hold light things.',
        question: 'Benny can take ONE thing across. Which should he take to keep the bridge safe?',
        options: ['A giant rock', 'A small flower', 'A heavy book', 'A big watermelon'],
        correct: 1,
        funFact: 'Engineers test bridges to make sure they are strong enough! They always think about weight.',
        encouragement: 'Smart choice! You think just like an engineer!',
      },
      tags: ['problem-solving', 'story', 'fun'],
      isOffline: false,
    },

    // COMMUNICATION - Early
    {
      id: 'act-004',
      title: 'Happy or Sad?',
      description: 'Look at the faces and match them to the right feeling! Learn about emotions.',
      skill: SkillArea.COMMUNICATION,
      ageGroup: [AgeGroup.EARLY],
      type: ActivityType.GAME,
      difficulty: 1,
      xpReward: 15,
      durationMin: 5,
      content: {
        story: 'Elmo the elephant has lots of feelings today! Can you help name them?',
        question: 'Elmo just dropped his ice cream on the floor. How is Elmo feeling?',
        options: ['Very happy', 'Excited', 'Sad and upset', 'Angry at everyone'],
        correct: 2,
        funFact: 'Naming our feelings helps us feel better! Scientists call this emotional labeling.',
        encouragement: 'You understand feelings so well! That is a superpower!',
      },
      tags: ['emotions', 'empathy', 'fun'],
      isOffline: true,
    },
    {
      id: 'act-005',
      title: 'The Asking Game',
      description: 'Learn how to ask for things nicely! Practice polite words.',
      skill: SkillArea.COMMUNICATION,
      ageGroup: [AgeGroup.EARLY],
      type: ActivityType.GAME,
      difficulty: 1,
      xpReward: 15,
      durationMin: 5,
      content: {
        story: 'Lily wants a cookie from grandma. Let us help her ask nicely!',
        question: 'Which is the NICEST way for Lily to ask for a cookie?',
        options: [
          'Give me cookie NOW!',
          'Grandma, may I please have a cookie?',
          'I want cookie! I want cookie!',
          'Cookie cookie cookie!',
        ],
        correct: 1,
        funFact: 'Saying please and thank you makes people feel respected and happy to help you!',
        encouragement: 'You know exactly how to use kind words! Wonderful!',
      },
      tags: ['polite', 'communication', 'story'],
      isOffline: true,
    },
    {
      id: 'act-006',
      title: 'Tell Me a Story!',
      description: 'Look at the pictures and pick what happens next in the story!',
      skill: SkillArea.COMMUNICATION,
      ageGroup: [AgeGroup.EARLY],
      type: ActivityType.GAME,
      difficulty: 2,
      xpReward: 20,
      durationMin: 7,
      content: {
        story: 'Tom woke up, got dressed, and picked up his school bag. What happened NEXT?',
        question: 'What do you think Tom did after picking up his school bag?',
        options: [
          'He went back to sleep',
          'He went to school',
          'He started cooking dinner',
          'He watched TV all day',
        ],
        correct: 1,
        funFact: 'Stories always have a beginning, middle and end. Being able to tell stories helps you share ideas!',
        encouragement: 'You are a fantastic storyteller! Keep it up!',
      },
      tags: ['storytelling', 'sequence', 'fun'],
      isOffline: true,
    },

    // SOCIAL EMOTIONAL - Early
    {
      id: 'act-007',
      title: 'The Sharing Tree',
      description: 'Help the forest friends learn to share! Discover why sharing feels good.',
      skill: SkillArea.SOCIAL_EMOTIONAL,
      ageGroup: [AgeGroup.EARLY],
      type: ActivityType.GAME,
      difficulty: 1,
      xpReward: 15,
      durationMin: 5,
      content: {
        story: 'Squirrel has 4 acorns. Rabbit has none and is very hungry.',
        question: 'What should Squirrel do to be a good friend?',
        options: [
          'Keep all 4 acorns',
          'Share some acorns with Rabbit',
          'Hide the acorns so Rabbit cannot see',
          'Run away quickly',
        ],
        correct: 1,
        funFact: 'Sharing makes BOTH people happy! Science shows that giving actually makes us feel better than receiving.',
        encouragement: 'You have a kind heart! Sharing is caring!',
      },
      tags: ['sharing', 'kindness', 'story'],
      isOffline: true,
    },
    {
      id: 'act-008',
      title: 'Calm Down Corner',
      description: 'Learn what to do when you feel angry or upset! Try these calming tricks.',
      skill: SkillArea.SOCIAL_EMOTIONAL,
      ageGroup: [AgeGroup.EARLY],
      type: ActivityType.GAME,
      difficulty: 1,
      xpReward: 15,
      durationMin: 5,
      content: {
        story: 'Max is very angry because his sister took his toy. He wants to shout and cry.',
        question: 'What is the BEST thing Max can do to calm down?',
        options: [
          'Shout as loud as he can',
          'Take 3 deep breaths and count to 10',
          'Throw his other toys',
          'Cry all day long',
        ],
        correct: 1,
        funFact: 'Deep breathing sends a signal to your brain to calm down! It really works in just 30 seconds.',
        encouragement: 'You know how to be calm and strong! That is amazing!',
      },
      tags: ['emotions', 'calm', 'mindfulness'],
      isOffline: true,
    },
    {
      id: 'act-009',
      title: 'The Sorry Garden',
      description: 'Learn why saying sorry matters and how to make things better!',
      skill: SkillArea.SOCIAL_EMOTIONAL,
      ageGroup: [AgeGroup.EARLY],
      type: ActivityType.GAME,
      difficulty: 2,
      xpReward: 20,
      durationMin: 7,
      content: {
        story: 'Mia accidentally knocked over Ben painting. Ben looks really sad.',
        question: 'What should Mia do to make Ben feel better?',
        options: [
          'Walk away quickly',
          'Say sorry and help Ben fix it',
          'Blame someone else',
          'Pretend it did not happen',
        ],
        correct: 1,
        funFact: 'A real sorry has 3 parts: say sorry, explain what you did wrong, and help fix it!',
        encouragement: 'You know how to be a true friend! Wonderful!',
      },
      tags: ['empathy', 'friendship', 'kindness'],
      isOffline: true,
    },

    // CREATIVITY - Early
    {
      id: 'act-010',
      title: 'The Colour Mixer',
      description: 'Mix colours to make new ones! Discover the magic of creativity.',
      skill: SkillArea.CREATIVITY,
      ageGroup: [AgeGroup.EARLY],
      type: ActivityType.GAME,
      difficulty: 1,
      xpReward: 15,
      durationMin: 5,
      content: {
        story: 'Pablo the painter ran out of green paint! He only has blue and yellow left.',
        question: 'What happens when Pablo mixes blue and yellow paint together?',
        options: ['He gets red', 'He gets green', 'He gets purple', 'He gets orange'],
        correct: 1,
        funFact: 'Blue + Yellow = Green! Red + Blue = Purple! Red + Yellow = Orange! These are called secondary colours.',
        encouragement: 'You are a colour genius! Artists everywhere would be proud!',
      },
      tags: ['colours', 'art', 'discovery'],
      isOffline: true,
    },
    {
      id: 'act-011',
      title: 'Build a Dream House',
      description: 'Design your dream house using imagination! There are no wrong answers.',
      skill: SkillArea.CREATIVITY,
      ageGroup: [AgeGroup.EARLY],
      type: ActivityType.GAME,
      difficulty: 2,
      xpReward: 20,
      durationMin: 7,
      content: {
        story: 'You get to design your very own dream house! It can be anything you imagine.',
        question: 'What would make your dream house the most special and fun?',
        options: [
          'A slide instead of stairs',
          'A swimming pool on the roof',
          'A room made entirely of trampolines',
          'All of these and more!',
        ],
        correct: 3,
        funFact: 'Architects are people who design buildings. They use their imagination every single day at work!',
        encouragement: 'Your imagination is incredible! Dream big always!',
      },
      tags: ['imagination', 'design', 'fun'],
      isOffline: true,
    },

    // DIGITAL LITERACY - Early
    {
      id: 'act-012',
      title: 'Safe or Not Safe Online?',
      description: 'Learn what is safe and not safe to do on the internet! Stay protected.',
      skill: SkillArea.DIGITAL_LITERACY,
      ageGroup: [AgeGroup.EARLY],
      type: ActivityType.GAME,
      difficulty: 1,
      xpReward: 15,
      durationMin: 5,
      content: {
        story: 'Zara got a new tablet! Her mum taught her some important internet rules.',
        question: 'A stranger online asks Zara for her home address. What should Zara do?',
        options: [
          'Tell them her address',
          'Tell them her school name instead',
          'Say NO and tell mum or dad immediately',
          'Give them her phone number',
        ],
        correct: 2,
        funFact: 'Never share your address, phone number or school name with strangers online. Always tell a trusted adult!',
        encouragement: 'You know how to stay safe online! You are a digital superhero!',
      },
      tags: ['safety', 'internet', 'digital'],
      isOffline: true,
    },

    // ─── AGES 8-12 (MIDDLE) ───────────────────────────────────────────────────

    // CRITICAL THINKING - Middle
    {
      id: 'act-013',
      title: 'The Detective Challenge',
      description: 'Use clues to solve the mystery! Train your deduction skills.',
      skill: SkillArea.CRITICAL_THINKING,
      ageGroup: [AgeGroup.MIDDLE],
      type: ActivityType.GAME,
      difficulty: 2,
      xpReward: 20,
      durationMin: 8,
      content: {
        story: 'Detective Sam needs your help! Someone ate the last piece of birthday cake. Clue 1: The person has chocolate on their fingers. Clue 2: They were in the kitchen at 3pm. Clue 3: They said they were not hungry at lunch.',
        question: 'Based on the clues, who most likely ate the cake?',
        options: [
          'The person who was outside all day',
          'The person with chocolate fingers who was in the kitchen at 3pm',
          'The person who ate a big lunch',
          'The person who does not like chocolate',
        ],
        correct: 1,
        funFact: 'This is called deductive reasoning! Detectives, scientists and doctors all use this skill every day.',
        encouragement: 'Outstanding detective work! You cracked the case!',
      },
      tags: ['deduction', 'mystery', 'logic'],
      isOffline: false,
    },
    {
      id: 'act-014',
      title: 'Spot the Trick!',
      description: 'Can you spot the misleading information? Build your critical eye!',
      skill: SkillArea.CRITICAL_THINKING,
      ageGroup: [AgeGroup.MIDDLE],
      type: ActivityType.QUIZ,
      difficulty: 3,
      xpReward: 25,
      durationMin: 10,
      content: {
        story: 'An advertisement says: "9 out of 10 kids prefer ChocoPops cereal!" Sounds impressive right?',
        question: 'What important information is MISSING from this claim?',
        options: [
          'The price of the cereal',
          'How many kids were actually asked and who chose them',
          'What flavour the cereal is',
          'Where the cereal is made',
        ],
        correct: 1,
        funFact: 'Always ask: How many people were studied? Who chose them? Who paid for the study? These reveal the truth!',
        encouragement: 'Brilliant critical thinking! You cannot be fooled easily!',
      },
      tags: ['media-literacy', 'critical-thinking', 'advertising'],
      isOffline: false,
    },
    {
      id: 'act-015',
      title: 'The Bridge Builder',
      description: 'Choose the strongest bridge design using logical thinking!',
      skill: SkillArea.CRITICAL_THINKING,
      ageGroup: [AgeGroup.MIDDLE],
      type: ActivityType.SIMULATION,
      difficulty: 3,
      xpReward: 25,
      durationMin: 10,
      content: {
        story: 'You are an engineer! You need to build a bridge that holds the most weight using limited materials.',
        question: 'Which bridge design is the STRONGEST based on engineering principles?',
        options: [
          'A flat plank with no supports',
          'A triangle-based truss design',
          'A single arch with no reinforcement',
          'Many thin sticks placed loosely',
        ],
        correct: 1,
        funFact: 'Triangles are the strongest shape in engineering! They distribute weight evenly and cannot be pushed out of shape.',
        encouragement: 'You think like a real engineer! Incredible!',
      },
      tags: ['engineering', 'STEM', 'problem-solving'],
      isOffline: false,
    },

    // COMMUNICATION - Middle
    {
      id: 'act-016',
      title: 'The Presentation Challenge',
      description: 'Choose the best way to present your ideas clearly!',
      skill: SkillArea.COMMUNICATION,
      ageGroup: [AgeGroup.MIDDLE],
      type: ActivityType.QUIZ,
      difficulty: 2,
      xpReward: 20,
      durationMin: 8,
      content: {
        story: 'Arjun has to present his science project to the class. He is nervous and does not know how to start.',
        question: 'What is the BEST opening line for Arjun to start his presentation confidently?',
        options: [
          'Um... so... I guess I will talk about plants now...',
          'Did you know plants can communicate with each other? Today I will show you how!',
          'My project is about plants. Plants are green. Plants need water.',
          'I am not very good at this but here goes...',
        ],
        correct: 1,
        funFact: 'Starting with a surprising fact or question immediately grabs your audience attention! Great speakers always hook their listeners first.',
        encouragement: 'You know exactly how to capture an audience! Star presenter!',
      },
      tags: ['presentation', 'speaking', 'confidence'],
      isOffline: false,
    },
    {
      id: 'act-017',
      title: 'The Disagreement Game',
      description: 'Learn how to disagree respectfully! A vital life skill.',
      skill: SkillArea.COMMUNICATION,
      ageGroup: [AgeGroup.MIDDLE],
      type: ActivityType.SIMULATION,
      difficulty: 3,
      xpReward: 25,
      durationMin: 10,
      content: {
        story: 'Your friend says homework should be banned completely. You think some homework is useful. You want to share your view without hurting the friendship.',
        question: 'Which response shows the BEST respectful disagreement?',
        options: [
          'You are completely wrong about that!',
          'I see your point, but I think some homework helps us practise. What if we had less but better homework?',
          'Whatever, you do not know anything.',
          'You are right, homework should definitely be banned.',
        ],
        correct: 1,
        funFact: 'Saying "I see your point, but..." shows you listened AND have your own view. This is called assertive communication!',
        encouragement: 'You are a communication champion! People love talking with you!',
      },
      tags: ['disagreement', 'respect', 'assertive'],
      isOffline: false,
    },

    // SOCIAL EMOTIONAL - Middle
    {
      id: 'act-018',
      title: 'The Friendship Test',
      description: 'Identify what makes a true friend in tricky situations!',
      skill: SkillArea.SOCIAL_EMOTIONAL,
      ageGroup: [AgeGroup.MIDDLE],
      type: ActivityType.SIMULATION,
      difficulty: 2,
      xpReward: 20,
      durationMin: 8,
      content: {
        story: 'Your best friend got the lead role in the school play. You auditioned too but did not get it. You feel disappointed and a little jealous.',
        question: 'What is the MOST mature and kind thing to do?',
        options: [
          'Ignore your friend and stop talking to them',
          'Tell everyone the teacher made a mistake',
          'Congratulate your friend sincerely and cheer them on',
          'Pretend you did not want the role anyway',
        ],
        correct: 2,
        funFact: 'Being happy for others even when you are disappointed is called being magnanimous. It is one of the hardest and most respected qualities!',
        encouragement: 'You have the heart of a true champion! Amazing emotional strength!',
      },
      tags: ['friendship', 'jealousy', 'empathy'],
      isOffline: false,
    },
    {
      id: 'act-019',
      title: 'Bully Buster Challenge',
      description: 'Learn the right way to handle bullying situations safely!',
      skill: SkillArea.SOCIAL_EMOTIONAL,
      ageGroup: [AgeGroup.MIDDLE],
      type: ActivityType.SIMULATION,
      difficulty: 3,
      xpReward: 25,
      durationMin: 10,
      content: {
        story: 'You see a classmate being teased by a group of older students in the playground. The classmate looks upset and scared.',
        question: 'What is the SAFEST and most helpful thing you can do?',
        options: [
          'Walk away and pretend you did not see it',
          'Confront the bullies alone and tell them to stop',
          'Get a trusted adult immediately and check on the classmate later',
          'Video it and post it online',
        ],
        correct: 2,
        funFact: 'Research shows that when bystanders get an adult involved, bullying stops within 10 seconds in 57% of cases! You have the power to help!',
        encouragement: 'You are a true upstander not a bystander! The world needs more people like you!',
      },
      tags: ['bullying', 'courage', 'safety'],
      isOffline: false,
    },

    // CREATIVITY - Middle
    {
      id: 'act-020',
      title: 'The Invention Convention',
      description: 'Invent a solution to a real problem! Think like an innovator.',
      skill: SkillArea.CREATIVITY,
      ageGroup: [AgeGroup.MIDDLE],
      type: ActivityType.CHALLENGE,
      difficulty: 3,
      xpReward: 25,
      durationMin: 10,
      content: {
        story: 'The school canteen always runs out of the most popular lunch items by 12:30pm. Students who have late lunch are left with limited choices and feel disappointed.',
        question: 'Which solution shows the MOST creative and practical thinking?',
        options: [
          'Tell late lunch students to bring their own food',
          'Create a pre-order app where students choose their lunch in the morning',
          'Close the canteen at 12pm for everyone',
          'Make only one type of food to avoid running out',
        ],
        correct: 1,
        funFact: 'This is exactly how apps like Swiggy and Zomato were invented! Someone saw a problem and created a creative solution.',
        encouragement: 'You think like a startup founder! Absolutely brilliant!',
      },
      tags: ['innovation', 'problem-solving', 'design-thinking'],
      isOffline: false,
    },
    {
      id: 'act-021',
      title: 'Story Remix Studio',
      description: 'Take a classic story and flip it in a creative new way!',
      skill: SkillArea.CREATIVITY,
      ageGroup: [AgeGroup.MIDDLE],
      type: ActivityType.CREATIVE_TASK,
      difficulty: 2,
      xpReward: 20,
      durationMin: 8,
      content: {
        story: 'In the original story, Cinderella waits to be rescued by a prince. But what if we flipped the story?',
        question: 'Which remix shows the MOST creative and original thinking?',
        options: [
          'Cinderella still goes to the ball but wears different clothes',
          'Cinderella starts her own business, becomes successful and does not need rescuing at all',
          'The prince goes to the ball instead',
          'Cinderella stays home and watches TV',
        ],
        correct: 1,
        funFact: 'Remixing stories is how most movies are made! Many famous films are just classic stories told in completely new ways.',
        encouragement: 'You are a creative genius! Hollywood better watch out!',
      },
      tags: ['storytelling', 'creativity', 'remix'],
      isOffline: false,
    },

    // DIGITAL LITERACY - Middle
    {
      id: 'act-022',
      title: 'Fake News Detective',
      description: 'Can you spot fake news from real news? A critical skill for today!',
      skill: SkillArea.DIGITAL_LITERACY,
      ageGroup: [AgeGroup.MIDDLE],
      type: ActivityType.QUIZ,
      difficulty: 3,
      xpReward: 25,
      durationMin: 10,
      content: {
        story: 'You see this headline on social media: "BREAKING: Scientists confirm that homework causes brain damage!" It has 50,000 shares.',
        question: 'What should you do FIRST before believing or sharing this?',
        options: [
          'Share it immediately because it has many likes',
          'Check if it is reported by established news sources like BBC or Times of India',
          'Believe it because scientists said it',
          'Share it only with close friends',
        ],
        correct: 1,
        funFact: 'Over 60% of people share news articles without reading beyond the headline! Always verify before you amplify.',
        encouragement: 'You are a certified fake news detector! The internet needs more people like you!',
      },
      tags: ['fake-news', 'media-literacy', 'critical-thinking'],
      isOffline: false,
    },
    {
      id: 'act-023',
      title: 'Password Power Up',
      description: 'Test your password security knowledge! Protect your digital life.',
      skill: SkillArea.DIGITAL_LITERACY,
      ageGroup: [AgeGroup.MIDDLE],
      type: ActivityType.QUIZ,
      difficulty: 2,
      xpReward: 20,
      durationMin: 8,
      content: {
        story: 'Rohan uses the password "rohan2012" for all his accounts. His friend says this is dangerous.',
        question: 'Why is "rohan2012" a weak password?',
        options: [
          'It is too long',
          'It uses personal info that is easy to guess and is used for all accounts',
          'It has numbers in it',
          'It starts with a lowercase letter',
        ],
        correct: 1,
        funFact: 'Using your name and birth year as a password can be cracked in under 1 second by modern computers! Use random words and symbols instead.',
        encouragement: 'You are a cybersecurity expert in the making! Stay safe online!',
      },
      tags: ['cybersecurity', 'password', 'digital-safety'],
      isOffline: false,
    },

    // ─── AGES 13-17 (TEEN) ────────────────────────────────────────────────────

    // CRITICAL THINKING - Teen
    {
      id: 'act-024',
      title: 'The Bias Blind Spot',
      description: 'Discover your thinking biases and learn to overcome them!',
      skill: SkillArea.CRITICAL_THINKING,
      ageGroup: [AgeGroup.TEEN],
      type: ActivityType.SIMULATION,
      difficulty: 3,
      xpReward: 30,
      durationMin: 12,
      content: {
        story: 'Scenario: A study claims that students who eat breakfast score 20% higher on tests. Your school wants to make breakfast mandatory based on this single study.',
        question: 'As a critical thinker on the student council, what is your MOST important concern?',
        options: [
          'Whether the study was peer-reviewed, had a large sample size, and considered other factors like sleep and income',
          'Whether the breakfast was tasty',
          'Whether the study was done recently',
          'Whether the school can afford to provide breakfast',
        ],
        correct: 0,
        funFact: 'Correlation does not equal causation! Students who eat breakfast may also have more stable home lives, which could explain the higher scores.',
        encouragement: 'Outstanding analytical thinking! You would make an incredible researcher!',
      },
      tags: ['bias', 'research', 'critical-thinking'],
      isOffline: false,
    },
    {
      id: 'act-025',
      title: 'The Ethical Dilemma',
      description: 'Navigate a real-world ethical challenge using logical reasoning!',
      skill: SkillArea.CRITICAL_THINKING,
      ageGroup: [AgeGroup.TEEN],
      type: ActivityType.SIMULATION,
      difficulty: 4,
      xpReward: 35,
      durationMin: 15,
      content: {
        story: 'You discover your best friend has been copying homework from online sources and submitting it as their own work. They have been doing this for months and are getting top grades. You are struggling honestly. Exams are in 2 weeks.',
        question: 'Which response best balances integrity, friendship, and fairness?',
        options: [
          'Start copying homework too since everyone does it',
          'Report your friend anonymously to the teacher immediately',
          'Talk to your friend privately about the risks and encourage them to stop before exams',
          'Ignore it completely as it is not your problem',
        ],
        correct: 2,
        funFact: 'This type of dilemma tests moral reasoning. Research shows people who can navigate ethical dilemmas thoughtfully make better leaders and decision-makers.',
        encouragement: 'You have exceptional moral clarity and emotional intelligence!',
      },
      tags: ['ethics', 'integrity', 'dilemma'],
      isOffline: false,
    },

    // COMMUNICATION - Teen
    {
      id: 'act-026',
      title: 'The Negotiation Room',
      description: 'Master the art of negotiation in a real-world scenario!',
      skill: SkillArea.COMMUNICATION,
      ageGroup: [AgeGroup.TEEN],
      type: ActivityType.SIMULATION,
      difficulty: 4,
      xpReward: 35,
      durationMin: 15,
      content: {
        story: 'You want to extend your phone curfew from 9pm to 11pm. Your parents are firm at 9pm for health reasons. You have researched that teenagers need adequate social connection for mental health.',
        question: 'Which negotiation approach is most likely to succeed?',
        options: [
          'Demand the change and say all your friends have no curfew',
          'Present your research, propose a trial period of 2 weeks at 10pm, and offer to maintain your grades',
          'Sulk and refuse to talk until they agree',
          'Ask your grandparents to convince your parents',
        ],
        correct: 1,
        funFact: 'The best negotiations create win-win outcomes. Presenting evidence, showing responsibility and proposing compromises are used by top business negotiators worldwide!',
        encouragement: 'You negotiate like a CEO! Absolutely impressive communication skills!',
      },
      tags: ['negotiation', 'persuasion', 'communication'],
      isOffline: false,
    },
    {
      id: 'act-027',
      title: 'Digital Footprint Audit',
      description: 'Learn how your online presence affects your real-world opportunities!',
      skill: SkillArea.COMMUNICATION,
      ageGroup: [AgeGroup.TEEN],
      type: ActivityType.SIMULATION,
      difficulty: 3,
      xpReward: 30,
      durationMin: 12,
      content: {
        story: 'Priya is applying for a prestigious summer internship at a tech company. The recruiter Googles her name and finds an old social media post where she made fun of a classmate 2 years ago.',
        question: 'What does this situation teach us about digital communication?',
        options: [
          'Never use social media if you want a career',
          'Everything posted online can affect future opportunities, so think before you post',
          'Only private accounts are safe',
          'Recruiters should not check social media',
        ],
        correct: 1,
        funFact: '70% of employers check social media before hiring. Your digital footprint is your permanent public resume!',
        encouragement: 'You understand digital responsibility at a professional level! Very impressive!',
      },
      tags: ['digital-footprint', 'career', 'communication'],
      isOffline: false,
    },

    // SOCIAL EMOTIONAL - Teen
    {
      id: 'act-028',
      title: 'The Peer Pressure Lab',
      description: 'Navigate real peer pressure scenarios with confidence!',
      skill: SkillArea.SOCIAL_EMOTIONAL,
      ageGroup: [AgeGroup.TEEN],
      type: ActivityType.SIMULATION,
      difficulty: 4,
      xpReward: 35,
      durationMin: 15,
      content: {
        story: 'At a friend group hangout, some friends start making fun of a student from another class who is not present. They look at you expecting you to join in. You feel uncomfortable but do not want to seem uncool.',
        question: 'Which response shows the highest emotional intelligence?',
        options: [
          'Join in to avoid being left out',
          'Stay silent and change the subject naturally',
          'Say clearly but calmly that you are not comfortable with this and suggest doing something else',
          'Leave without saying anything',
        ],
        correct: 2,
        funFact: 'Standing up to peer pressure actually increases respect from peers over time. People admire those with clear values even if they do not show it immediately.',
        encouragement: 'You have rock-solid emotional intelligence and courage! Remarkable!',
      },
      tags: ['peer-pressure', 'courage', 'integrity'],
      isOffline: false,
    },
    {
      id: 'act-029',
      title: 'Stress Management Toolkit',
      description: 'Build your personal stress management strategy for exams and life!',
      skill: SkillArea.SOCIAL_EMOTIONAL,
      ageGroup: [AgeGroup.TEEN],
      type: ActivityType.SIMULATION,
      difficulty: 3,
      xpReward: 30,
      durationMin: 12,
      content: {
        story: 'Board exams are in 3 weeks. You have 6 subjects to revise and feel overwhelmed. You have been sleeping only 4-5 hours and skipping meals. Your anxiety is increasing daily.',
        question: 'Which approach will MOST effectively manage your stress and maximise performance?',
        options: [
          'Study 18 hours a day and sleep after exams',
          'Create a balanced schedule with study blocks, 7-8 hours sleep, meals and short breaks',
          'Stop studying and hope for the best',
          'Study only your favourite subjects',
        ],
        correct: 1,
        funFact: 'Research from Stanford shows that adequate sleep improves memory retention by up to 40%! Studying less but sleeping more can actually increase your scores.',
        encouragement: 'You have mastered the science of peak performance! Future you will thank present you!',
      },
      tags: ['stress', 'exam', 'wellbeing'],
      isOffline: false,
    },

    // CREATIVITY - Teen
    {
      id: 'act-030',
      title: 'The Social Impact Challenge',
      description: 'Design a creative solution to a real social problem!',
      skill: SkillArea.CREATIVITY,
      ageGroup: [AgeGroup.TEEN],
      type: ActivityType.CHALLENGE,
      difficulty: 4,
      xpReward: 35,
      durationMin: 15,
      content: {
        story: 'In your city, elderly people are increasingly isolated and lonely, while teenagers are looking for meaningful volunteer opportunities and community service hours.',
        question: 'Which solution MOST creatively addresses BOTH problems simultaneously?',
        options: [
          'Set up a food delivery service for elderly people',
          'Create a skill-swap programme where teens teach technology to elderly people and elderly people teach life skills and stories to teens',
          'Build more retirement homes',
          'Create a social media page for elderly people',
        ],
        correct: 1,
        funFact: 'This type of solution is called a social innovation. Companies like Airbnb and Uber were built on similar creative thinking that solved two problems at once!',
        encouragement: 'You think like a social entrepreneur! This world needs your ideas!',
      },
      tags: ['social-impact', 'innovation', 'community'],
      isOffline: false,
    },

    // DIGITAL LITERACY - Teen
    {
      id: 'act-031',
      title: 'AI Ethics Explorer',
      description: 'Navigate the ethical challenges of AI in the real world!',
      skill: SkillArea.DIGITAL_LITERACY,
      ageGroup: [AgeGroup.TEEN],
      type: ActivityType.SIMULATION,
      difficulty: 4,
      xpReward: 35,
      durationMin: 15,
      content: {
        story: 'A school wants to use an AI system that predicts which students are likely to fail exams based on attendance and grades. Students identified as at-risk will receive extra support but will also be tracked more closely.',
        question: 'What is the MOST important ethical concern with this AI system?',
        options: [
          'The AI might be too expensive for the school',
          'The AI could create self-fulfilling prophecies and may be biased against certain student groups',
          'Students might not like being monitored',
          'Teachers might lose their jobs',
        ],
        correct: 1,
        funFact: 'This is called algorithmic bias. AI systems trained on historical data can perpetuate existing inequalities. This is one of the biggest challenges in tech ethics today!',
        encouragement: 'You think about technology at a graduate level! Extraordinary insight!',
      },
      tags: ['AI', 'ethics', 'technology'],
      isOffline: false,
    },

    // ─── AGES 18-20 (YOUNG ADULT) ─────────────────────────────────────────────

    // CRITICAL THINKING - Young Adult
    {
      id: 'act-032',
      title: 'The Investment Dilemma',
      description: 'Apply critical thinking to a real-world financial decision!',
      skill: SkillArea.CRITICAL_THINKING,
      ageGroup: [AgeGroup.YOUNG_ADULT],
      type: ActivityType.SIMULATION,
      difficulty: 5,
      xpReward: 40,
      durationMin: 15,
      content: {
        story: 'You have saved Rs 50,000. Three options: Option A - Fixed Deposit at 7% guaranteed. Option B - Stock market with potential 15% return but also potential 20% loss. Option C - A friend business idea with promised 30% return in 3 months.',
        question: 'Which option shows the BEST critical financial thinking for a young adult?',
        options: [
          'Option C because 30% return sounds amazing',
          'Option B because stocks always go up eventually',
          'Option A because guaranteed returns are best for an emergency fund, with perhaps a small allocation to Option B',
          'Keep cash at home to avoid all risk',
        ],
        correct: 2,
        funFact: 'Most financial experts recommend an emergency fund in safe instruments before investing in volatile assets. Option C sounds like a potential fraud scheme!',
        encouragement: 'You think like a seasoned financial analyst! Your future financial health is in great hands!',
      },
      tags: ['finance', 'decision-making', 'critical-thinking'],
      isOffline: false,
    },

    // COMMUNICATION - Young Adult
    {
      id: 'act-033',
      title: 'The Job Interview Master',
      description: 'Ace real-world job interview scenarios with strategic communication!',
      skill: SkillArea.COMMUNICATION,
      ageGroup: [AgeGroup.YOUNG_ADULT],
      type: ActivityType.SIMULATION,
      difficulty: 4,
      xpReward: 35,
      durationMin: 15,
      content: {
        story: 'In a job interview the interviewer asks: "Tell me about a time you failed and what you learned from it." Most candidates either deny failing or get defensive.',
        question: 'Which response demonstrates the HIGHEST communication intelligence?',
        options: [
          'I have never really failed at anything important',
          'During my internship I missed a project deadline. I took ownership, communicated proactively with my team, implemented a personal task management system and subsequently delivered all projects on time. It taught me that systems beat willpower.',
          'I failed once but it was not really my fault',
          'Everyone fails, it is not a big deal',
        ],
        correct: 1,
        funFact: 'This is called the STAR method: Situation, Task, Action, Result. Top companies like Google and Amazon specifically train interviewers to look for this structure in answers!',
        encouragement: 'You communicate with the sophistication of a seasoned professional! Any employer would be lucky to have you!',
      },
      tags: ['interview', 'career', 'communication'],
      isOffline: false,
    },

    // SOCIAL EMOTIONAL - Young Adult
    {
      id: 'act-034',
      title: 'The Workplace Conflict',
      description: 'Navigate a complex workplace situation with emotional intelligence!',
      skill: SkillArea.SOCIAL_EMOTIONAL,
      ageGroup: [AgeGroup.YOUNG_ADULT],
      type: ActivityType.SIMULATION,
      difficulty: 4,
      xpReward: 35,
      durationMin: 15,
      content: {
        story: 'Your manager publicly criticised your work in front of the entire team in a way that felt unfair and humiliating. You are angry and other colleagues noticed. You have a one-on-one meeting with your manager tomorrow.',
        question: 'Which approach demonstrates the highest emotional and professional intelligence?',
        options: [
          'Confront your manager aggressively in the meeting',
          'Say nothing and bottle up your feelings',
          'Calmly share how the public feedback affected you, ask for private feedback in future, and focus the discussion on how to improve your work',
          'Complain to all your colleagues about the manager',
        ],
        correct: 2,
        funFact: 'This approach uses assertive communication, emotional regulation and focuses on solutions rather than blame. These are exactly the skills that differentiate high performers in every workplace!',
        encouragement: 'You have the emotional sophistication of an exceptional leader! Truly impressive!',
      },
      tags: ['workplace', 'conflict', 'professional'],
      isOffline: false,
    },

    // CREATIVITY - Young Adult
    {
      id: 'act-035',
      title: 'The Startup Challenge',
      description: 'Apply creative thinking to build a viable business idea!',
      skill: SkillArea.CREATIVITY,
      ageGroup: [AgeGroup.YOUNG_ADULT],
      type: ActivityType.CHALLENGE,
      difficulty: 5,
      xpReward: 40,
      durationMin: 15,
      content: {
        story: 'You notice that college students in your city struggle to find affordable, healthy food near campus. Most options are either expensive healthy food or cheap unhealthy food.',
        question: 'Which business idea MOST creatively and viably solves this problem?',
        options: [
          'Open a restaurant near campus with regular pricing',
          'Create a subscription meal-prep service where students pay weekly for healthy tiffin boxes made by local home cooks, reducing costs through bulk buying',
          'Start a food blog with healthy recipes',
          'Petition the college to improve their canteen',
        ],
        correct: 1,
        funFact: 'This is called the platform business model! Companies like Airbnb and Ola did not own hotels or cars. They connected people who had resources with people who needed them. This model is incredibly scalable!',
        encouragement: 'You think like a world-class entrepreneur! This idea could genuinely change lives!',
      },
      tags: ['startup', 'entrepreneurship', 'creativity'],
      isOffline: false,
    },

    // DIGITAL LITERACY - Young Adult
    {
      id: 'act-036',
      title: 'Digital Privacy Master',
      description: 'Understand and protect your digital privacy in the modern world!',
      skill: SkillArea.DIGITAL_LITERACY,
      ageGroup: [AgeGroup.YOUNG_ADULT],
      type: ActivityType.SIMULATION,
      difficulty: 4,
      xpReward: 35,
      durationMin: 15,
      content: {
        story: 'A popular free app wants access to your contacts, location, camera, microphone and storage. The app is a simple flashlight app. It has 10 million downloads and 4.5 star rating.',
        question: 'What does this situation indicate and what should you do?',
        options: [
          'Accept all permissions because the app is popular and highly rated',
          'This is a data harvesting red flag. A flashlight needs only screen brightness access. Deny all other permissions or find an alternative app.',
          'Accept because free apps need data to survive',
          'Only accept location access',
        ],
        correct: 1,
        funFact: 'This is a classic data harvesting technique. Your contacts, location and microphone data can be sold for hundreds of dollars per user profile to advertisers and data brokers!',
        encouragement: 'You have mastered digital self-defence! Your data and privacy are safe with you in charge!',
      },
      tags: ['privacy', 'data', 'digital-safety'],
      isOffline: false,
    },
  ]

  for (const activity of activities) {
    await prisma.activity.upsert({
      where: { id: activity.id },
      update: activity,
      create: activity,
    })
  }

  console.log('Seeded ' + badges.length + ' badges and ' + activities.length + ' activities')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
